services:

  dev:
    build:
      context: .
      target: dev
    image: template:dev
    container_name: template_dev_container
    volumes:
      - type: bind
        source: .
        target: /repo
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
