# Run python unit tests

name: docker tests

on:
  push:
  schedule:
    -
      cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        target: dev
        push: false
        tags: ${{ secrets.REPO_NAME }}:gha
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:cache,mode=max
        outputs: type=docker
    -
      name: Unit tests
      run: docker run ${{ secrets.REPO_NAME }}:gha poetry run pytest
    -
      name: Style tests
      run: docker run ${{ secrets.REPO_NAME }}:gha poetry run pre-commit run --all-files
