# Run python unit tests

name: tests

on:
  push:
  schedule:
    -
      cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    -
      name: Install `poetry`
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    -
      name: Install
      run: python -m poetry install --with dev
    -
      name: `pytest`
      run: poetry run pytest
    - 
      name: `mypy`
      run: poetry run mypy .
    - 
      name: `ruff format`
      run: poetry run ruff format
    - 
      name: `ruff check`
      run: poetry run ruff check