# Run python unit tests

name: tests

on:
  push:
  schedule:
    -
      cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    -
      name: Install uv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
    -
      name: Install
      run: python -m uv sync --all-extras
    -
      name: pytest
      run: python -m uv run pytest
    - 
      name: mypy
      run: python -m uv run mypy .
    - 
      name: ruff format
      run: python -m uv run ruff format
    - 
      name: ruff check
      run: python -m uv run ruff check