# Run python unit tests

name: tests

on:
  push:
  schedule:
    -
      cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    -
      name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install -r requirements/prod.txt
        python -m pip install -r requirements/dev.txt
    -
      name: Build
      run: |
        python -m build
        python -m pip install -e . --no-deps
    -
      name: Unit tests
      run: pytest
    -
      name: Style tests
      run: pre-commit run --all-files
