# Run python unit tests

name: tests

on:
  push:
  schedule:
    -
      cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    -
      name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    -
      name: Install dependencies
        python -m poetry install --with dev,pre-commit --with pre-commit
    -
      name: Unit tests
      run: pytest
    -
      name: Style tests
      run: pre-commit run --all-files
